"""
Folder ID: _.Load

Description: The runtime tree Weaver deploys this item's load code into.

Lineage: Generated by Weaver from the item's own authored source.

File key: "**/*"

Incremental: false

Static: true
"""
from weaver import Folder


class ___Load(Folder):
    def read(self):
        return self.staging_folder(), []
