"""Weaver's central catalogue, scoped by logical item.

An installation is identified by ``(item_type, item_name)`` and an object by
that item identity plus ``(schema_name, object_name)``. Files objects use
``Files/<schema>`` as their catalogue schema, so the same four-part identity
covers them without a namespace column.
"""

from __future__ import annotations

from .connection import CatalogueConnection, catalogue_connection
from .render import (
    InstallationScope,
    Row,
    column_set,
    render_delete_obsolete,
    render_delete_scope,
    render_merge,
    sorted_rows,
)
from .state import (
    Catalogue,
    Reconciliation,
    RegisteredDocument,
    catalogue_for,
    catalogue_in,
    for_targets,
    read_catalogue_state,
    reconcile_catalogue_state,
    retaining,
)
from .tables import (
    AUDIT_COLUMN_NAMES,
    BOOKMARK,
    CATALOGUE_SCHEMA,
    COLUMN_DICTIONARY,
    CURRENT_STATE_TABLES,
    DEPENDENCY,
    DICTIONARY_TABLES,
    FOLDER_DICTIONARY,
    FOREIGN_KEY_DICTIONARY,
    HISTORY_TABLES,
    INSTALLATION,
    ITEM_SCOPE_COLUMNS,
    KEY_DICTIONARY,
    KEY_PRIMARY,
    KEY_UNIQUE,
    LOAD_STATISTIC,
    LOAD_STATUS,
    LOG,
    OBJECT_ROLES,
    OBJECT_TYPES,
    STANDARD_SURFACE_TABLES,
    PROJECTED_TABLES,
    REGISTRY,
    ROLE_DATA,
    ROLE_LOAD,
    RUNTIME_TABLES,
    SCHEMA_DICTIONARY,
    SHORTCUT,
    SIGNATURE,
    TABLE_DICTIONARY,
    TEST_STATUS,
    CatalogueColumn,
    CatalogueTable,
    RuntimeTable,
    table,
)

__all__ = [
    "SHORTCUT",
    "AUDIT_COLUMN_NAMES",
    "BOOKMARK",
    "CURRENT_STATE_TABLES",
    "HISTORY_TABLES",
    "LOAD_STATISTIC",
    "LOAD_STATUS",
    "LOG",
    "STANDARD_SURFACE_TABLES",
    "RUNTIME_TABLES",
    "RuntimeTable",
    "TEST_STATUS",
    "CATALOGUE_SCHEMA",
    "PROJECTED_TABLES",
    "catalogue_for",
    "catalogue_in",
    "COLUMN_DICTIONARY",
    "CatalogueColumn",
    "CatalogueTable",
    "DEPENDENCY",
    "DICTIONARY_TABLES",
    "FOLDER_DICTIONARY",
    "FOREIGN_KEY_DICTIONARY",
    "KEY_DICTIONARY",
    "INSTALLATION",
    "ITEM_SCOPE_COLUMNS",
    "InstallationScope",
    "KEY_PRIMARY",
    "KEY_UNIQUE",
    "OBJECT_ROLES",
    "OBJECT_TYPES",
    "REGISTRY",
    "ROLE_DATA",
    "ROLE_LOAD",
    "Row",
    "SCHEMA_DICTIONARY",
    "SIGNATURE",
    "TABLE_DICTIONARY",
    "column_set",
    "CatalogueConnection",
    "catalogue_connection",
    "render_delete_obsolete",
    "render_delete_scope",
    "render_merge",
    "sorted_rows",
    "table",
    "RegisteredDocument",
    "Catalogue",
    "Reconciliation",
    "retaining",
    "for_targets",
    "read_catalogue_state",
    "reconcile_catalogue_state",
]
