"""SES policy — the contract an authored object must satisfy."""

from __future__ import annotations

from .dependencies import (
    RelationReference,
    extract_python_references,
    extract_sql_references,
)
from .columns import (
    metadata_column_references,
    resolve_build_columns,
    validate_build_columns,
)
from .graph import Edge, Graph
from .repository import (
    DependencyEdge,
    SesRepository,
    build_internal_graph,
    effective_dependencies,
    read_repository,
    unresolved_references,
)
from .schemas import (
    SCHEMAS_DIRECTORY,
    SchemaSes,
    is_schema_file,
    parse_schema_document,
    read_schema_document,
)
from .source import (
    SourceDocument,
    SqlAnalysis,
    analyse_sql,
    content_hash,
    language_for_filename,
    object_id_for_filename,
    read_source_document,
)
from .references import (
    IDENTITY_COLUMN_NOTE,
    ResolvedText,
    column_note,
    declared_column_notes,
    resolve_text,
)
from .metadata import (
    AUDIT_COLUMNS,
    AUDIT_DELETE,
    AUDIT_INSERT,
    AUDIT_UPDATE,
    FOLDER,
    DELTA_LANGUAGES,
    LAKEHOUSE_NAMESPACE,
    LANGUAGES,
    NAMESPACES,
    OBJECT_KINDS,
    PYTHON,
    SPARK_SQL,
    SQL,
    TABLE,
    VIEW,
    WAREHOUSE_NAMESPACE,
    Column,
    ForeignKey,
    MetadataText,
    ObjectId,
    Reference,
    Revision,
    SesDocument,
    audit_column_name,
    extract_python_metadata,
    extract_sql_metadata_and_body,
    namespace_for_target,
    parse_document,
    parse_python_document,
    parse_sql_document,
)

__all__ = [
    "RelationReference",
    "extract_python_references",
    "extract_sql_references",
    "SesRepository",
    "DependencyEdge",
    "read_repository",
    "Graph",
    "Edge",
    "build_internal_graph",
    "effective_dependencies",
    "unresolved_references",
    "SchemaSes",
    "SCHEMAS_DIRECTORY",
    "is_schema_file",
    "parse_schema_document",
    "read_schema_document",
    "LAKEHOUSE_NAMESPACE",
    "WAREHOUSE_NAMESPACE",
    "NAMESPACES",
    "namespace_for_target",
    "SourceDocument",
    "SqlAnalysis",
    "analyse_sql",
    "content_hash",
    "language_for_filename",
    "object_id_for_filename",
    "read_source_document",
    "FOLDER",
    "TABLE",
    "VIEW",
    "OBJECT_KINDS",
    "PYTHON",
    "SQL",
    "SPARK_SQL",
    "LANGUAGES",
    "DELTA_LANGUAGES",
    "AUDIT_COLUMNS",
    "AUDIT_INSERT",
    "AUDIT_UPDATE",
    "AUDIT_DELETE",
    "audit_column_name",
    "Column",
    "ForeignKey",
    "MetadataText",
    "ObjectId",
    "Reference",
    "Revision",
    "SesDocument",
    "IDENTITY_COLUMN_NOTE",
    "ResolvedText",
    "column_note",
    "declared_column_notes",
    "resolve_text",
    "extract_python_metadata",
    "extract_sql_metadata_and_body",
    "parse_document",
    "parse_python_document",
    "parse_sql_document",
    "metadata_column_references",
    "resolve_build_columns",
    "validate_build_columns",
]
