"""Building the catalogue through the ordinary build path, on local Delta.

This is the bootstrap argument made concrete. The built-in repository is
materialised into the Weaver Lakehouse's repos area, a bundle is generated by the
ordinary planner and installed by the ordinary installer, and ten Delta tables
appear. Nothing in the path knows it is building a catalogue — there is no
catalogue-specific create, no privileged executor and no special-cased schema.

What is asserted is the *shape* the catalogue representation claims: the tables
exist, their columns and types match the definitions column for column, and the
declared keys are physically not null.

The build here is generated with ``catalogue=False``, so the subject stays the
physical creation of the tables — a build creates structure. Populating them is
catalogue DML, and the whole bootstrap (create *and* populate, in one bundle) is
``test_catalogue_setup``.
"""

from __future__ import annotations

import pytest

from weaver import ItemRef
from weaver.build_bundle.bundle import load_bundle
from weaver.build_bundle.installer import InstallationEnvironment, install_bundle
from weaver.build_bundle.planner import generate_item_build_bundle
from weaver.build_bundle.targets import ItemBinding, ItemBindings, LakehouseBinding
from weaver.catalogue.builtin import materialise_builtin_item
from weaver.catalogue.tables import CATALOGUE_TABLES
from weaver.declaration import read_weaver_repository
from weaver.declaration.model import WeaverItemId

pytestmark = pytest.mark.spark


@pytest.fixture
def built_catalogue(lakehouses, spark, weaver_catalogue):
    """The built-in repository, installed into the Weaver Lakehouse itself.

    The Weaver Lakehouse is both the control plane and, uniquely for this one
    repository, the destination — the catalogue's tables are Weaver's own.
    """

    resolver, store = lakehouses.resolver, lakehouses.store
    repository_root = resolver.weaver_items_root
    materialise_builtin_item(repository_root, store=store)
    repository = read_weaver_repository(repository_root, store=store)
    control = LakehouseBinding(lakehouse=lakehouses.weaver)

    bundle = generate_item_build_bundle(
        repository,
        bindings=ItemBindings(
            (ItemBinding(WeaverItemId.parse("Lakehouse/_weaver"), control),)
        ),
        output=resolver.build_bundle("catalogue-bootstrap"),
        store=store,
        prune=False,
        # Structure only. With the catalogue on, this same bundle would go on to
        # populate the tables it just created — which is the bootstrap, and is
        # tested as such in test_catalogue_setup.
        catalogue=False,
        control_lakehouse=None,
        resolver=resolver,
        spark=spark,
        host=lakehouses.host,
    )
    report = install_bundle(
        load_bundle(bundle.location, store=store),
        environment=InstallationEnvironment(store=store, resolver=resolver, spark=spark),
    )
    assert report.status == "succeeded", _failures(report)
    # `weaver_catalogue` created schema `_` and drops it again afterwards: one
    # Spark catalogue is shared by every test while each gets its own Lakehouse
    # directory, so a schema left registered would make the next test's create a
    # no-op and send its tables here.
    return bundle, report


def _failures(report) -> str:
    return "\n".join(
        f"{action.action_id}: {action.error_type}: {action.error_message}"
        for sequence in report.sequences
        for action in sequence.actions
        if action.status == "failed"
    )


def test_the_ordinary_build_path_creates_all_ten_catalogue_tables(
    built_catalogue, weaver_catalogue
):
    """The emulator preserves the same canonical display names as Fabric."""

    assert set(weaver_catalogue.tables("_")) == {
        table.name for table in CATALOGUE_TABLES
    }


def test_each_table_has_exactly_the_columns_the_representation_declares(
    built_catalogue, spark, weaver_catalogue
):
    for table in CATALOGUE_TABLES:
        fields = spark.table(weaver_catalogue.qualify("_", table.name)).schema.fields
        assert [field.name for field in fields] == list(table.physical_columns), table.name


def test_each_column_has_the_declared_type(built_catalogue, spark, weaver_catalogue):
    for table in CATALOGUE_TABLES:
        types = {
            field.name: field.dataType.simpleString()
            for field in spark.table(weaver_catalogue.qualify("_", table.name)).schema.fields
        }
        for column in table.columns:
            assert types[column.name] == column.type, f"{table.name}.{column.name}"
        for audit in ("row_insert_datetime", "row_update_datetime", "row_delete_datetime"):
            assert types[audit] == "timestamp"


def test_the_declared_key_is_physically_not_null(built_catalogue, spark, weaver_catalogue):
    """The representation asserts key columns are not null; the built table proves it.

    Nullability comes from the Weaver document ``Primary key`` declaration, so this closes the
    loop between what the catalogue claims about its identity columns and what
    Delta will actually enforce.
    """

    for table in CATALOGUE_TABLES:
        nullable = {
            field.name: field.nullable
            for field in spark.table(weaver_catalogue.qualify("_", table.name)).schema.fields
        }
        for column in table.columns:
            assert nullable[column.name] is not column.not_null, (
                f"{table.name}.{column.name}"
            )


def test_the_audit_columns_are_not_null_so_a_live_row_needs_its_sentinel(
    built_catalogue, spark, weaver_catalogue
):
    for table in CATALOGUE_TABLES:
        nullable = {
            field.name: field.nullable
            for field in spark.table(weaver_catalogue.qualify("_", table.name)).schema.fields
        }
        assert nullable["row_delete_datetime"] is False, table.name


def test_a_freshly_built_catalogue_holds_no_rows(built_catalogue, spark, weaver_catalogue):
    """Build creates structure. Populating the catalogue is separate DML.

    Which is why the tables are empty here and populated in test_catalogue_setup:
    the difference between the two is exactly the catalogue sequences.
    """

    for table in CATALOGUE_TABLES:
        assert spark.table(weaver_catalogue.qualify("_", table.name)).count() == 0, table.name


def test_the_bundle_is_an_ordinary_bundle_with_no_catalogue_specific_action(
    built_catalogue,
):
    """No privileged path: every action is one the planner emits for any repository.

    The catalogue tables are created by ``create_schema`` and ``build_table``,
    through ``spark_schema`` and ``spark_table`` — the same actions and the same
    executors an application repository gets. Nothing here knows it is building a
    catalogue.
    """

    bundle, _report = built_catalogue
    kinds = {action.kind for _s, _b, action in bundle.plan.actions()}
    assert kinds == {"create_schema", "build_table"}
    executors = {action.executor for _s, _b, action in bundle.plan.actions()}
    assert executors == {"spark_schema", "spark_table"}


def test_the_tables_land_under_the_weaver_lakehouse_tables_area(
    built_catalogue, lakehouses
):
    """Addressed where Weaver resolves them, not in Spark's own warehouse directory."""

    tables_root = lakehouses.resolver.tables_root(ItemRef("Weaver"))
    directories = {
        entry.name
        for entry in lakehouses.store.list(tables_root / "_")
        if entry.is_directory
    }
    assert directories == {table.name for table in CATALOGUE_TABLES}


def test_rebuilding_the_unchanged_repository_succeeds_again(built_catalogue, lakehouses, spark):
    """Re-building the unchanged repository is safe and identical.

    Note what this does *not* yet claim: build still emits
    ``CREATE OR REPLACE TABLE``, so a rebuild empties the tables. That is
    deliberate for this branch — dropping only what changed needs the signatures
    the catalogue is being built to hold, and the drop policy that reads them.
    Until then, re-running setup is idempotent in *shape* and destructive of
    *rows*, and only setup does it.
    """

    resolver, store = lakehouses.resolver, lakehouses.store
    repository = read_weaver_repository(resolver.weaver_items_root, store=store)
    control = LakehouseBinding(lakehouse=lakehouses.weaver)
    bundle = generate_item_build_bundle(
        repository,
        bindings=ItemBindings(
            (ItemBinding(WeaverItemId.parse("Lakehouse/_weaver"), control),)
        ),
        output=resolver.build_bundle("catalogue-bootstrap-again"),
        store=store,
        prune=False,
        # Structure only. With the catalogue on, this same bundle would go on to
        # populate the tables it just created — which is the bootstrap, and is
        # tested as such in test_catalogue_setup.
        catalogue=False,
        resolver=resolver,
        spark=spark,
        host=lakehouses.host,
    )
    report = install_bundle(
        load_bundle(bundle.location, store=store),
        environment=InstallationEnvironment(store=store, resolver=resolver, spark=spark),
    )
    assert report.status == "succeeded", _failures(report)
    first, _ = built_catalogue
    # Same repository content, so the same bundle identity — determinism (§10).
    assert bundle.plan.bundle_id == first.plan.bundle_id
