"""Building the catalogue through the ordinary build path, on local Delta.

This is the bootstrap argument made concrete. The built-in item is composed in
memory, a bundle is generated by the ordinary planner and installed by the
ordinary installer, and ten Delta tables appear. Nothing in the path knows it is
building a catalogue — there is no
catalogue-specific create, no privileged executor and no special-cased schema.

What is asserted is the *shape* the catalogue representation claims: the tables
exist, their columns and types match the definitions column for column, and the
declared keys are physically not null.

Catalogue publication is mandatory, so the same ordinary bundle creates the
tables, describes them and certifies them last.
"""

from __future__ import annotations

import pytest

from weaver.targets import ItemRef
from weaver.catalogue.tables import CATALOGUE_TABLES, INSTALLATION, REGISTRY
from weaver.initialise import initialise_weaver_lakehouse

pytestmark = pytest.mark.spark


@pytest.fixture
def built_catalogue(lakehouses, spark, weaver_catalogue):
    """The built-in repository, installed into the Weaver Lakehouse itself.

    The Weaver Lakehouse is both the control plane and, uniquely for this one
    repository, the destination — the catalogue's tables are Weaver's own.
    """

    resolver, store = lakehouses.resolver, lakehouses.store
    store.make_directory(resolver.weaver_items_root)
    result = initialise_weaver_lakehouse(
        weaver_lakehouse=lakehouses.weaver,
        workspace=lakehouses.workspace,
        store=store,
        spark=spark,
        output=resolver.build_bundle("catalogue-bootstrap"),
    )
    assert result.report.status == "succeeded", _failures(result.report)
    # `weaver_catalogue` created schema `_` and drops it again afterwards: one
    # Spark catalogue is shared by every test while each gets its own Lakehouse
    # directory, so a schema left registered would make the next test's create a
    # no-op and send its tables here.
    return result.plan, result.report


def _failures(report) -> str:
    return "\n".join(
        f"{action.action_id}: {action.error_type}: {action.error_message}"
        for sequence in report.sequences
        for action in sequence.actions
        if action.status == "failed"
    )


def test_the_ordinary_build_path_creates_all_ten_catalogue_tables(
    built_catalogue, weaver_catalogue
):
    """The emulator preserves the same canonical display names as Fabric."""

    assert set(weaver_catalogue.tables("_")) == {
        table.name for table in CATALOGUE_TABLES
    }


def test_each_table_has_exactly_the_columns_the_representation_declares(
    built_catalogue, spark, weaver_catalogue
):
    for table in CATALOGUE_TABLES:
        fields = spark.table(weaver_catalogue.qualify("_", table.name)).schema.fields
        assert [field.name for field in fields] == list(table.physical_columns), table.name


def test_each_column_has_the_declared_type(built_catalogue, spark, weaver_catalogue):
    for table in CATALOGUE_TABLES:
        types = {
            field.name: field.dataType.simpleString()
            for field in spark.table(weaver_catalogue.qualify("_", table.name)).schema.fields
        }
        for column in table.columns:
            assert types[column.name] == column.type, f"{table.name}.{column.name}"
        for audit in ("row_insert_datetime", "row_update_datetime", "row_delete_datetime"):
            assert types[audit] == "timestamp"


def test_the_declared_key_is_physically_not_null(built_catalogue, spark, weaver_catalogue):
    """The representation asserts key columns are not null; the built table proves it.

    Nullability comes from the Weaver document ``Primary key`` declaration, so this closes the
    loop between what the catalogue claims about its identity columns and what
    Delta will actually enforce.
    """

    for table in CATALOGUE_TABLES:
        nullable = {
            field.name: field.nullable
            for field in spark.table(weaver_catalogue.qualify("_", table.name)).schema.fields
        }
        for column in table.columns:
            assert nullable[column.name] is not column.not_null, (
                f"{table.name}.{column.name}"
            )


def test_the_audit_columns_are_not_null_so_a_live_row_needs_its_sentinel(
    built_catalogue, spark, weaver_catalogue
):
    for table in CATALOGUE_TABLES:
        nullable = {
            field.name: field.nullable
            for field in spark.table(weaver_catalogue.qualify("_", table.name)).schema.fields
        }
        assert nullable["row_delete_datetime"] is False, table.name


def test_a_freshly_built_catalogue_is_published_and_certified(
    built_catalogue, spark, weaver_catalogue
):
    assert spark.table(weaver_catalogue.qualify("_", INSTALLATION.name)).count() == 1
    # Every table, plus the one Folder the control plane declares: `_.Log`, the
    # task log. It is certified like any other artefact because it is one.
    assert spark.table(weaver_catalogue.qualify("_", REGISTRY.name)).count() == (
        len(CATALOGUE_TABLES) + 1
    )


def test_the_bundle_is_an_ordinary_bundle_with_no_catalogue_specific_action(
    built_catalogue,
):
    """No privileged path: every action is one the planner emits for any repository.

    The catalogue tables are created by ``build_table`` through ``spark_table``
    — the same action and executor an application repository gets. The prepared
    inventory already contains schema ``_``, so the ordinary planner correctly
    omits a schema creation action. The endpoint refresh is likewise the ordinary
    one: the control Lakehouse is a Lakehouse, and its own tables just changed.
    Nothing here knows it is building a catalogue.
    """

    plan, _report = built_catalogue
    kinds = {action.kind for _s, _b, action in plan.actions()}
    assert {
        "build_table",
        "build_folder",
        "publish_catalogue",
        "publish_registry",
        "refresh_sql_endpoint",
    } <= kinds
    assert "create_schema" not in kinds
    executors = {action.executor for _s, _b, action in plan.actions()}
    assert executors == {
        "spark_table",
        # The task log is a declared Folder, so it is created by the ordinary
        # folder executor — the same one an application repository's folder gets.
        "folder",
        "spark_sql_batch",
        "sql_endpoint_refresh",
    }


def test_the_tables_land_under_the_weaver_lakehouse_tables_area(
    built_catalogue, lakehouses
):
    """Addressed where Weaver resolves them, not in Spark's own warehouse directory."""

    tables_root = lakehouses.resolver.tables_root(ItemRef("Weaver"))
    directories = {
        entry.name
        for entry in lakehouses.store.list(tables_root / "_")
        if entry.is_directory
    }
    assert directories == {table.name for table in CATALOGUE_TABLES}


def test_rebuilding_the_unchanged_repository_succeeds_again(
    built_catalogue, lakehouses, spark, weaver_catalogue
):
    """Re-building is safe and preserves the already-published catalogue rows."""

    resolver, store = lakehouses.resolver, lakehouses.store
    result = initialise_weaver_lakehouse(
        weaver_lakehouse=lakehouses.weaver,
        workspace=lakehouses.workspace,
        store=store,
        spark=spark,
        output=resolver.build_bundle("catalogue-bootstrap-again"),
    )
    assert result.report.status == "succeeded", _failures(result.report)
    assert spark.table(weaver_catalogue.qualify("_", REGISTRY.name)).count() == (
        len(CATALOGUE_TABLES) + 1
    )
